### PR TITLE
Add tagging controller (have yet to add tagging to motions views).

### PR DESCRIPTION
**Pull request by btelles**
Okay, this should be ready for pulling into master.
(as far as I can tell)... Would someone please pull this? :-)

### CODE REVIEW

**Comment by barrettclark** [comment]
Do you use blueprint in any of the views?  There is already a lot of CSS included in the page for the overall jQuery chrome.  What does blueprint do for us that isn't already in place?  I've never used it, so I honestly don't know.

**Comment by btelles** [comment]
Hi Barrett, :-)
Sure, I use it in the new 'tags#index' view where it divides the list of tags into 3 evenly-spaced columns. 

Here's a description of what the scss mixin does:
http://compass-style.org/docs/reference/blueprint/grid/

And here's the documentation for blueprint that is specific to blueprint grids:
http://compass-style.org/docs/reference/blueprint/grid/

(In all honesty, I find the YUI Grids CSS tool easier to use than blueprint's grid, but I think compass only comes with blueprint...they dropped YUI a while ago).

**Comment by thedelchop** [comment]
Here Bernardo, I pulled this in but its got some merge conflicts, can you pull from master, update them and then I'll pull it down?

**Comment by btelles** [comment]
Joseph,
Thanks. I merged the results and tested that we're all green/yellow in rspec and cucumber. This should make us happy for a while...adding more tests right now just for good measure, but you should be able to pull now. (Or I can commit to master if you want.)
Cheers,
Bernie

**Pull request merged**
