### PR TITLE
Cleaning up a few web steps (trying to live up to the rest of the team's quality work)

### PR DESCRIPTION
**Pull request by btelles**

### CODE REVIEW

**Comment by btelles** [comment]
Hi guys. Could you help me improve my code by letting me know why this wasn't accepted last night?

**Comment by thedelchop** [comment]
Sure, when I pulled in your request, I got 5 failures in "member_seconds_motion" and "member_votes" is incomplete.  Also, you  have a couple of issues with your whitespace.  Pull in the latest changes from wycats/jquery-governance, and rerun rake.  ONce you're all green, post it here and I pull in.

**Comment by thedelchop** [comment]
P.S. If you are having trouble make "member_seconds_motion" green, IM me Joseph.DelCioppio@gmail.com and I'll be happy to help you.

**Comment by btelles** [comment]
Thanks Joseph, I'm on it :-)

**Comment by dtrasbo** [comment]
Hey Bernie,

I can see you've made some changes to the creation motions feature in the commits above to clean it up a bit.  That's good. I hadn't seen that, though, so I've already pushed some of the same changes you made (https://github.com/wycats/jquery-governance/commit/90b9fc6a9c3dc080545130b1f0ec7302ef7cee8c). Sorry about that. I basically went through all the features and made them conform the the Cucumber Conventions doc and did that one while I was at it.

**Comment by btelles** [comment]
David, that was an honest mistake, so no problem. :-)

Guys, we have to decide whether it's okay to commit unimplemented features. Joseph, you mentioned that it's not allowed, but David, you just committed several of them. I'm pretty sure I heard Yehuda mention it was okay to commit unimplemented changes at least once (in campfire).

There's also the issue of features that use unimplemented steps. David, I think (let me know if I'm wrong) that some of the features you committed just now did not have steps that would allow them to be tested. One of the reasons I've been late on committing more is because I've been implementing features, web steps, and the application all in one go...which might not be optimal because it makes for longer periods between commits, and for more blind coding where we can't tell if we're duplicating work. 

Could you let me know what you think?

Regards,
Bernie

**Comment by dtrasbo** [comment]
As a matter of fact I didn't commit any unfinished features. I merely cleaned up the feature files that already existed, making them conform to our conventions.

That said, what I'd suggest is to commit regularly on your local machine, then push to your fork in one go and send a pull request - for maximum flow.

**Comment by btelles** [comment]
Okie dokie...my fault for calling you out specifically...guess we'll figure everything out at the campfire :-)

**Pull request closed without merging**
